export const posts = [
  {
    id: 1,
    continent: "asia",
    category: "culture",
    date: "2024-10",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    featured: true,
    tags: ["templi", "natura", "fotografia"],
    translations: {
      it: {
        title: "Kyoto in Autunno",
        subtitle: "Tra i templi e le foglie rosse",
        destination: "Giappone",
        excerpt: "Camminare tra i vicoli di Gion al tramonto, mentre le maiko scivolano silenziose oltre i portoni di legno scuro. Kyoto in autunno è un sogno che si cammina.",
        body: `Camminare tra i vicoli di Gion al tramonto, mentre le maiko scivolano silenziose oltre i portoni di legno scuro. Kyoto in autunno è un sogno che si cammina.\n\nI momiji — gli aceri giapponesi — tingono i giardini di rosso lacca e arancio bruciato. Al tempio Tofuku-ji la folla si ammassa sui ponti di legno per fotografare il mare di foglie, ma basta allontanarsi di pochi passi per ritrovare il silenzio.\n\nHo dormito in un ryokan nel quartiere di Higashiyama. Ogni mattina: yukata, colazione kaiseki, il suono del legno che scricchiola. Kyoto insegna la lentezza come nessun altro posto al mondo.`,
      },
      en: {
        title: "Kyoto in Autumn",
        subtitle: "Among temples and red leaves",
        destination: "Japan",
        excerpt: "Walking through the alleys of Gion at sunset, as maiko glide silently past dark wooden gates. Kyoto in autumn is a dream you walk through.",
        body: `Walking through the alleys of Gion at sunset, as maiko glide silently past dark wooden gates. Kyoto in autumn is a dream you walk through.\n\nThe momiji — Japanese maples — paint the gardens in lacquer red and burnt orange. At Tofuku-ji temple, crowds gather on wooden bridges to photograph the sea of leaves, but a few steps away you can find silence again.\n\nI stayed in a ryokan in the Higashiyama district. Every morning: yukata, kaiseki breakfast, the sound of creaking wood. Kyoto teaches slowness like nowhere else in the world.`,
      },
      fr: {
        title: "Kyoto en Automne",
        subtitle: "Entre temples et feuilles rouges",
        destination: "Japon",
        excerpt: "Se promener dans les ruelles de Gion au coucher du soleil, tandis que les maiko glissent silencieusement devant les portes en bois sombre. Kyoto en automne est un rêve que l'on marche.",
        body: `Se promener dans les ruelles de Gion au coucher du soleil, tandis que les maiko glissent silencieusement devant les portes en bois sombre. Kyoto en automne est un rêve que l'on marche.\n\nLes momiji — les érables japonais — teintent les jardins de rouge laque et d'orange brûlé. Au temple Tofuku-ji, la foule se presse sur les ponts en bois pour photographier la mer de feuilles, mais il suffit de s'éloigner de quelques pas pour retrouver le silence.\n\nJ'ai dormi dans un ryokan dans le quartier d'Higashiyama. Chaque matin : yukata, petit-déjeuner kaiseki, le bruit du bois qui craque. Kyoto enseigne la lenteur comme nulle part ailleurs au monde.`,
      },
      es: {
        title: "Kioto en Otoño",
        subtitle: "Entre templos y hojas rojas",
        destination: "Japón",
        excerpt: "Caminar por los callejones de Gion al atardecer, mientras las maiko se deslizan silenciosamente por las puertas de madera oscura. Kioto en otoño es un sueño que se camina.",
        body: `Caminar por los callejones de Gion al atardecer, mientras las maiko se deslizan silenciosamente por las puertas de madera oscura. Kioto en otoño es un sueño que se camina.\n\nLos momiji — los arces japoneses — tiñen los jardines de rojo laca y naranja quemado. En el templo Tofuku-ji, la multitud se agolpa en los puentes de madera para fotografiar el mar de hojas, pero basta alejarse unos pasos para encontrar el silencio de nuevo.\n\nMe hospedé en un ryokan en el barrio de Higashiyama. Cada mañana: yukata, desayuno kaiseki, el sonido de la madera crujiendo. Kioto enseña la lentitud como ningún otro lugar del mundo.`,
      },
      de: {
        title: "Kyoto im Herbst",
        subtitle: "Zwischen Tempeln und roten Blättern",
        destination: "Japan",
        excerpt: "Durch die Gassen von Gion bei Sonnenuntergang wandern, während Maiko lautlos an dunklen Holztoren vorbeischweben. Kyoto im Herbst ist ein Traum, den man durchschreitet.",
        body: `Durch die Gassen von Gion bei Sonnenuntergang wandern, während Maiko lautlos an dunklen Holztoren vorbeischweben. Kyoto im Herbst ist ein Traum, den man durchschreitet.\n\nDie Momiji — japanische Ahornbäume — färben die Gärten in Lackrot und gebranntes Orange. Am Tofuku-ji-Tempel drängen sich die Massen auf Holzbrücken, um das Meer aus Blättern zu fotografieren, doch ein paar Schritte weiter findet man wieder Stille.\n\nIch schlief in einem Ryokan im Viertel Higashiyama. Jeden Morgen: Yukata, Kaiseki-Frühstück, das Knarren des Holzes. Kyoto lehrt die Langsamkeit wie kein anderer Ort der Welt.`,
      },
    },
  },
  {
    id: 2,
    continent: "america",
    category: "adventure",
    date: "2024-03",
    readTime: 12,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    featured: true,
    tags: ["trekking", "natura", "ghiacciai"],
    translations: {
      it: {
        title: "Patagonia Selvaggia",
        subtitle: "Fine del mondo, inizio di tutto",
        destination: "Argentina",
        excerpt: "I ghiacciai del Perito Moreno crepitano come tuoni lontani. Qui il vento non chiede permesso e il silenzio è più rumoroso di qualsiasi città.",
        body: `I ghiacciai del Perito Moreno crepitano come tuoni lontani. Qui il vento non chiede permesso e il silenzio è più rumoroso di qualsiasi città.\n\nHo camminato per cinque giorni nel Parco Nazionale Torres del Paine. Lo zaino pesava venti chili, le vesciche alle ginocchia erano reali, ma ogni curva del sentiero rivelava qualcosa di impossibile.\n\nLa Patagonia non è un posto per chi vuole stare comodo. È un posto per chi vuole sentirsi piccolo nel modo migliore possibile.`,
      },
      en: {
        title: "Wild Patagonia",
        subtitle: "End of the world, beginning of everything",
        destination: "Argentina",
        excerpt: "The Perito Moreno glaciers crackle like distant thunder. Here the wind asks no permission and the silence is louder than any city.",
        body: `The Perito Moreno glaciers crackle like distant thunder. Here the wind asks no permission and the silence is louder than any city.\n\nI walked for five days in Torres del Paine National Park. The backpack weighed twenty kilos, the blisters on my knees were real, but every bend in the trail revealed something impossible.\n\nPatagonia is not a place for those who want to be comfortable. It's a place for those who want to feel small in the best possible way.`,
      },
      fr: {
        title: "Patagonie Sauvage",
        subtitle: "Bout du monde, début de tout",
        destination: "Argentine",
        excerpt: "Les glaciers du Perito Moreno craquent comme un tonnerre lointain. Ici le vent ne demande pas la permission et le silence est plus bruyant que n'importe quelle ville.",
        body: `Les glaciers du Perito Moreno craquent comme un tonnerre lointain. Ici le vent ne demande pas la permission et le silence est plus bruyant que n'importe quelle ville.\n\nJ'ai marché pendant cinq jours dans le Parc National Torres del Paine. Le sac à dos pesait vingt kilos, les ampoules aux genoux étaient bien réelles, mais chaque virage du sentier révélait quelque chose d'impossible.\n\nLa Patagonie n'est pas un endroit pour ceux qui veulent être à l'aise. C'est un endroit pour ceux qui veulent se sentir petits de la meilleure façon possible.`,
      },
      es: {
        title: "Patagonia Salvaje",
        subtitle: "Fin del mundo, principio de todo",
        destination: "Argentina",
        excerpt: "Los glaciares del Perito Moreno crujen como truenos lejanos. Aquí el viento no pide permiso y el silencio es más ruidoso que cualquier ciudad.",
        body: `Los glaciares del Perito Moreno crujen como truenos lejanos. Aquí el viento no pide permiso y el silencio es más ruidoso que cualquier ciudad.\n\nCaminé durante cinco días en el Parque Nacional Torres del Paine. La mochila pesaba veinte kilos, las ampollas en las rodillas eran reales, pero cada curva del sendero revelaba algo imposible.\n\nLa Patagonia no es un lugar para quienes quieren estar cómodos. Es un lugar para quienes quieren sentirse pequeños de la mejor manera posible.`,
      },
      de: {
        title: "Wilde Patagonien",
        subtitle: "Ende der Welt, Anfang von allem",
        destination: "Argentinien",
        excerpt: "Die Gletscher des Perito Moreno knacken wie ferner Donner. Hier fragt der Wind nicht um Erlaubnis und die Stille ist lauter als jede Stadt.",
        body: `Die Gletscher des Perito Moreno knacken wie ferner Donner. Hier fragt der Wind nicht um Erlaubnis und die Stille ist lauter als jede Stadt.\n\nIch wanderte fünf Tage im Nationalpark Torres del Paine. Der Rucksack wog zwanzig Kilo, die Blasen an den Knien waren real, aber jede Biegung des Weges enthüllte etwas Unmögliches.\n\nPatagonien ist kein Ort für diejenigen, die es bequem haben wollen. Es ist ein Ort für diejenigen, die sich auf die beste Art und Weise klein fühlen wollen.`,
      },
    },
  },
  {
    id: 3,
    continent: "africa",
    category: "culture",
    date: "2024-04",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80",
    featured: false,
    tags: ["medina", "gastronomia", "artigianato"],
    translations: {
      it: { title: "Marrakech al Tramonto", subtitle: "Spezie, colori e labirinti", destination: "Marocco", excerpt: "La medina ti inghiotte. Ti perdi tra i suk profumati di cumino e rosa, tra artigiani che battono il rame con ritmo antico. Perdersi è il punto.", body: `La medina ti inghiotte. Ti perdi tra i suk profumati di cumino e rosa, tra artigiani che battono il rame con ritmo antico. Perdersi è il punto.\n\nJemaa el-Fna si trasforma al tramonto. I musicisti gnawa, i venditori di succo d'arancia, i cantastorie berberi. È uno spettacolo che esiste da secoli e non si è mai stancato di esistere.\n\nHo mangiato il miglior tajine della mia vita in un vicolo senza nome, seduto su un tappeto logoro, mentre fuori il mondo andava avanti veloce.` },
      en: { title: "Marrakech at Sunset", subtitle: "Spices, colors and labyrinths", destination: "Morocco", excerpt: "The medina swallows you whole. You get lost among souks scented with cumin and rose, among craftsmen hammering copper with ancient rhythm. Getting lost is the point.", body: `The medina swallows you whole. You get lost among souks scented with cumin and rose, among craftsmen hammering copper with ancient rhythm. Getting lost is the point.\n\nJemaa el-Fna transforms at sunset. Gnawa musicians, orange juice vendors, Berber storytellers. It's a spectacle that has existed for centuries and has never tired of existing.\n\nI ate the best tajine of my life in a nameless alley, sitting on a worn carpet, while outside the world rushed on.` },
      fr: { title: "Marrakech au Coucher du Soleil", subtitle: "Épices, couleurs et labyrinthes", destination: "Maroc", excerpt: "La médina vous engloutit. On se perd dans les souks parfumés de cumin et de rose, parmi les artisans qui martelent le cuivre d'un rythme ancien. Se perdre, c'est le but.", body: `La médina vous engloutit. On se perd dans les souks parfumés de cumin et de rose, parmi les artisans qui martelent le cuivre d'un rythme ancien. Se perdre, c'est le but.\n\nJemaa el-Fna se transforme au coucher du soleil. Les musiciens gnawa, les vendeurs de jus d'orange, les conteurs berbères. C'est un spectacle qui existe depuis des siècles et ne s'est jamais lassé d'exister.\n\nJ'ai mangé le meilleur tajine de ma vie dans une ruelle sans nom, assis sur un tapis usé, pendant que dehors le monde continuait à toute vitesse.` },
      es: { title: "Marrakech al Atardecer", subtitle: "Especias, colores y laberintos", destination: "Marruecos", excerpt: "La medina te engulle. Te pierdes entre los zocos perfumados de comino y rosa, entre artesanos que golpean el cobre con ritmo ancestral. Perderse es el punto.", body: `La medina te engulle. Te pierdes entre los zocos perfumados de comino y rosa, entre artesanos que golpean el cobre con ritmo ancestral. Perderse es el punto.\n\nJemaa el-Fna se transforma al atardecer. Los músicos gnawa, los vendedores de zumo de naranja, los cuentacuentos bereberes. Es un espectáculo que existe desde hace siglos y nunca se ha cansado de existir.\n\nComí el mejor tajín de mi vida en un callejón sin nombre, sentado en una alfombra gastada, mientras afuera el mundo seguía a toda velocidad.` },
      de: { title: "Marrakesch bei Sonnenuntergang", subtitle: "Gewürze, Farben und Labyrinthe", destination: "Marokko", excerpt: "Die Medina verschluckt dich. Du verlierst dich in Souks, die nach Kreuzkümmel und Rose duften, unter Handwerkern, die Kupfer im alten Rhythmus hämmern. Sich zu verlieren ist der Sinn.", body: `Die Medina verschluckt dich. Du verlierst dich in Souks, die nach Kreuzkümmel und Rose duften, unter Handwerkern, die Kupfer im alten Rhythmus hämmern. Sich zu verlieren ist der Sinn.\n\nJemaa el-Fna verwandelt sich bei Sonnenuntergang. Gnawa-Musiker, Orangensaftverkäufer, Berber-Geschichtenerzähler. Es ist ein Spektakel, das seit Jahrhunderten existiert und es nie müde geworden ist zu existieren.\n\nIch aß das beste Tajine meines Lebens in einer namenlosen Gasse, auf einem abgenutzten Teppich sitzend, während draußen die Welt weiterlief.` },
    },
  },
  {
    id: 4,
    continent: "europe",
    category: "nature",
    date: "2024-01",
    readTime: 10,
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80",
    featured: false,
    tags: ["aurora boreale", "vulcani", "paesaggi"],
    translations: {
      it: { title: "Islanda: Terra di Ghiaccio e Fuoco", subtitle: "Aurora boreale alle 3 di notte", destination: "Islanda", excerpt: "Guidare sulla Ring Road con la neve che sfuma l'orizzonte. Poi, all'improvviso, il cielo esplode di verde.", body: `Guidare sulla Ring Road con la neve che sfuma l'orizzonte. Poi, all'improvviso, il cielo esplode di verde.\n\nL'aurora boreale non è come nelle foto. È viva. Pulsa. Si muove come un respiro cosmico sopra la tua testa e ti lascia senza parole.\n\nHo dormito in un furgone riscaldato vicino al ghiacciaio Vatnajökull. La mattina: geyser, cascate, vulcani fumanti. L'Islanda è il posto dove la Terra si ricorda di essere giovane.` },
      en: { title: "Iceland: Land of Ice and Fire", subtitle: "Northern lights at 3am", destination: "Iceland", excerpt: "Driving the Ring Road with snow blurring the horizon. Then, suddenly, the sky explodes in green.", body: `Driving the Ring Road with snow blurring the horizon. Then, suddenly, the sky explodes in green.\n\nThe northern lights are not like in photos. They are alive. They pulse. They move like a cosmic breath above your head and leave you speechless.\n\nI slept in a heated van near the Vatnajökull glacier. In the morning: geysers, waterfalls, smoking volcanoes. Iceland is the place where the Earth remembers it is young.` },
      fr: { title: "Islande : Terre de Glace et de Feu", subtitle: "Aurore boréale à 3h du matin", destination: "Islande", excerpt: "Conduire sur la Ring Road avec la neige qui estompe l'horizon. Puis, soudainement, le ciel explose en vert.", body: `Conduire sur la Ring Road avec la neige qui estompe l'horizon. Puis, soudainement, le ciel explose en vert.\n\nL'aurore boréale n'est pas comme sur les photos. Elle est vivante. Elle pulse. Elle se déplace comme un souffle cosmique au-dessus de votre tête et vous laisse sans voix.\n\nJ'ai dormi dans un van chauffé près du glacier Vatnajökull. Le matin : geysers, cascades, volcans fumants. L'Islande est l'endroit où la Terre se souvient qu'elle est jeune.` },
      es: { title: "Islandia: Tierra de Hielo y Fuego", subtitle: "Aurora boreal a las 3 de la madrugada", destination: "Islandia", excerpt: "Conducir por la Ring Road con la nieve difuminando el horizonte. Luego, de repente, el cielo explota en verde.", body: `Conducir por la Ring Road con la nieve difuminando el horizonte. Luego, de repente, el cielo explota en verde.\n\nLa aurora boreal no es como en las fotos. Está viva. Pulsa. Se mueve como un aliento cósmico sobre tu cabeza y te deja sin palabras.\n\nDormí en una furgoneta calefactada cerca del glaciar Vatnajökull. Por la mañana: géiseres, cascadas, volcanes humeantes. Islandia es el lugar donde la Tierra recuerda que es joven.` },
      de: { title: "Island: Land aus Eis und Feuer", subtitle: "Nordlichter um 3 Uhr nachts", destination: "Island", excerpt: "Auf der Ring Road fahren, während Schnee den Horizont verschwimmen lässt. Dann explodiert plötzlich der Himmel in Grün.", body: `Auf der Ring Road fahren, während Schnee den Horizont verschwimmen lässt. Dann explodiert plötzlich der Himmel in Grün.\n\nNordlichter sind nicht wie auf Fotos. Sie sind lebendig. Sie pulsieren. Sie bewegen sich wie ein kosmischer Atem über deinem Kopf und lassen dich sprachlos zurück.\n\nIch schlief in einem beheizten Van in der Nähe des Vatnajökull-Gletschers. Am Morgen: Geysire, Wasserfälle, rauchende Vulkane. Island ist der Ort, an dem die Erde sich daran erinnert, jung zu sein.` },
    },
  },
  {
    id: 5,
    continent: "asia",
    category: "food",
    date: "2024-02",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1509030450996-dd1a26dda07a?w=800&q=80",
    featured: false,
    tags: ["street food", "città", "mercati"],
    translations: {
      it: { title: "Hanoi: Il Caos Ordinato", subtitle: "Pho, motorini e poesia urbana", destination: "Vietnam", excerpt: "Sedersi su uno sgabellino di plastica alle sei del mattino, una ciotola di pho fumante tra le mani. Il traffico scorre intorno come un fiume.", body: `Sedersi su uno sgabellino di plastica alle sei del mattino, una ciotola di pho fumante tra le mani. Il traffico scorre intorno come un fiume. Hanoi non si capisce, si sente.\n\nIl quartiere antico ha 36 vie, ognuna dedicata a un mestiere. Via dei cestai, via degli argentieri, via dei cappellai. Una città che ha organizzato il caos meglio di qualsiasi altra.\n\nHo mangiato bun cha in un seminterrato, bevuto bia hoi a 25 centesimi, guardato le anatre al mercato del mattino. Hanoi entra dentro e non se ne va più.` },
      en: { title: "Hanoi: Ordered Chaos", subtitle: "Pho, motorbikes and urban poetry", destination: "Vietnam", excerpt: "Sitting on a plastic stool at six in the morning, a steaming bowl of pho in your hands. Traffic flows around like a river.", body: `Sitting on a plastic stool at six in the morning, a steaming bowl of pho in your hands. Traffic flows around like a river. Hanoi isn't understood, it's felt.\n\nThe old quarter has 36 streets, each dedicated to a craft. Street of the basket weavers, street of the silversmiths, street of the hatmakers. A city that has organized chaos better than any other.\n\nI ate bun cha in a basement, drank bia hoi for 25 cents, watched ducks at the morning market. Hanoi gets inside you and never leaves.` },
      fr: { title: "Hanoï : Chaos Ordonné", subtitle: "Pho, motos et poésie urbaine", destination: "Vietnam", excerpt: "S'asseoir sur un tabouret en plastique à six heures du matin, un bol de pho fumant entre les mains. La circulation coule autour comme une rivière.", body: `S'asseoir sur un tabouret en plastique à six heures du matin, un bol de pho fumant entre les mains. La circulation coule autour comme une rivière. Hanoï ne se comprend pas, elle se ressent.\n\nLe vieux quartier compte 36 rues, chacune dédiée à un métier. Rue des vanniers, rue des orfèvres, rue des chapeliers. Une ville qui a organisé le chaos mieux que n'importe quelle autre.\n\nJ'ai mangé du bun cha dans un sous-sol, bu de la bia hoi à 25 centimes, regardé les canards au marché du matin. Hanoï entre en vous et ne repart plus.` },
      es: { title: "Hanói: Caos Ordenado", subtitle: "Pho, motos y poesía urbana", destination: "Vietnam", excerpt: "Sentarse en un taburete de plástico a las seis de la mañana, con un cuenco humeante de pho entre las manos. El tráfico fluye alrededor como un río.", body: `Sentarse en un taburete de plástico a las seis de la mañana, con un cuenco humeante de pho entre las manos. El tráfico fluye alrededor como un río. Hanói no se entiende, se siente.\n\nEl barrio antiguo tiene 36 calles, cada una dedicada a un oficio. Calle de los cesteros, calle de los plateros, calle de los sombrereros. Una ciudad que ha organizado el caos mejor que cualquier otra.\n\nComí bun cha en un sótano, bebí bia hoi por 25 céntimos, observé los patos en el mercado matutino. Hanói se te mete dentro y ya no se va.` },
      de: { title: "Hanoi: Geordnetes Chaos", subtitle: "Pho, Motorräder und Stadtpoesie", destination: "Vietnam", excerpt: "Um sechs Uhr morgens auf einem Plastikhocker sitzen, eine dampfende Schüssel Pho in den Händen. Der Verkehr fließt ringsum wie ein Fluss.", body: `Um sechs Uhr morgens auf einem Plastikhocker sitzen, eine dampfende Schüssel Pho in den Händen. Der Verkehr fließt ringsum wie ein Fluss. Hanoi wird nicht verstanden, es wird gefühlt.\n\nDas alte Viertel hat 36 Straßen, jede einem Handwerk gewidmet. Straße der Korbflechter, Straße der Silberschmiede, Straße der Hutmacher. Eine Stadt, die das Chaos besser organisiert hat als jede andere.\n\nIch aß Bun Cha in einem Keller, trank Bia Hoi für 25 Cent, beobachtete Enten auf dem Morgenmarkt. Hanoi geht unter die Haut und verlässt einen nie mehr.` },
    },
  },
  {
    id: 6,
    continent: "europe",
    category: "sea",
    date: "2024-11",
    readTime: 5,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    featured: false,
    tags: ["mare", "isole", "off-season"],
    translations: {
      it: { title: "Santorini Fuori Stagione", subtitle: "L'isola quando appartiene solo a te", destination: "Grecia", excerpt: "Novembre a Oia: niente turisti, niente code ai tramonti. Solo tu, il mare blu oltremare, e il vento che porta profumo di sale.", body: `Novembre a Oia: niente turisti, niente code ai tramonti. Solo tu, il mare blu oltremare, e il vento che porta profumo di sale. Questo è il vero Egeo.\n\nI ristoranti aprono quando vogliono. I proprietari hanno tempo per parlare. Un pescatore mi ha offerto del vino seduto sulla banchina, raccontandomi la storia dell'isola come se fosse sua.\n\nSantorini fuori stagione è un'altra isola. Malinconica, autentica, bellissima. Consiglio a tutti di tornarci quando se ne sono andati tutti.` },
      en: { title: "Santorini Off Season", subtitle: "The island when it belongs only to you", destination: "Greece", excerpt: "November in Oia: no tourists, no queues for sunsets. Just you, the ultramarine blue sea, and wind carrying the scent of salt.", body: `November in Oia: no tourists, no queues for sunsets. Just you, the ultramarine blue sea, and wind carrying the scent of salt. This is the real Aegean.\n\nRestaurants open when they want. The owners have time to talk. A fisherman offered me wine sitting on the dock, telling me the island's story as if it were his own.\n\nSantorini off season is a different island. Melancholic, authentic, beautiful. I recommend everyone go back when everyone else has left.` },
      fr: { title: "Santorin Hors Saison", subtitle: "L'île quand elle n'appartient qu'à toi", destination: "Grèce", excerpt: "Novembre à Oia : pas de touristes, pas de files d'attente pour les couchers de soleil. Juste toi, la mer bleu outremer, et le vent qui porte le parfum du sel.", body: `Novembre à Oia : pas de touristes, pas de files d'attente pour les couchers de soleil. Juste toi, la mer bleu outremer, et le vent qui porte le parfum du sel. C'est la vraie mer Égée.\n\nLes restaurants ouvrent quand ils veulent. Les propriétaires ont le temps de parler. Un pêcheur m'a offert du vin assis sur le quai, me racontant l'histoire de l'île comme si c'était la sienne.\n\nSantorin hors saison est une autre île. Mélancolique, authentique, magnifique. Je conseille à tout le monde d'y retourner quand tout le monde est parti.` },
      es: { title: "Santorini Fuera de Temporada", subtitle: "La isla cuando solo te pertenece a ti", destination: "Grecia", excerpt: "Noviembre en Oia: sin turistas, sin colas para los atardeceres. Solo tú, el mar azul ultramarino, y el viento que trae aroma a sal.", body: `Noviembre en Oia: sin turistas, sin colas para los atardeceres. Solo tú, el mar azul ultramarino, y el viento que trae aroma a sal. Este es el verdadero Egeo.\n\nLos restaurantes abren cuando quieren. Los dueños tienen tiempo para hablar. Un pescador me ofreció vino sentado en el muelle, contándome la historia de la isla como si fuera suya.\n\nSantorini fuera de temporada es otra isla. Melancólica, auténtica, bellísima. Recomiendo a todos que vuelvan cuando todos los demás se hayan ido.` },
      de: { title: "Santorini Außerhalb der Saison", subtitle: "Die Insel, wenn sie nur dir gehört", destination: "Griechenland", excerpt: "November in Oia: keine Touristen, keine Schlangen für Sonnenuntergänge. Nur du, das ultramarinblaue Meer und der Wind, der Salzduft trägt.", body: `November in Oia: keine Touristen, keine Schlangen für Sonnenuntergänge. Nur du, das ultramarinblaue Meer und der Wind, der Salzduft trägt. Das ist die echte Ägäis.\n\nRestaurants öffnen, wann sie wollen. Die Besitzer haben Zeit zum Reden. Ein Fischer bot mir Wein an, während er auf dem Dock saß, und erzählte mir die Geschichte der Insel, als wäre sie seine eigene.\n\nSantorini außerhalb der Saison ist eine andere Insel. Melancholisch, authentisch, wunderschön. Ich empfehle jedem, zurückzukehren, wenn alle anderen gegangen sind.` },
    },
  },
];
